language: python

# Allow shinken to run on new travis infra
sudo: False

# Allow cache of downloads
cache: pip

python:
  - "2.6"
  - "2.7"
  
# command to install dependencies
# some are only used for travis/coveralls so we are installing them here only
install:
  - ./test/setup_test.sh
# command to run tests

script:
  - cd test
  - ./quick_tests.sh

# specific call to launch coverage data into coveralls.io
after_success:
  coveralls
